### ISSUE TITLE
Template Import Problems

### ISSUE THREAD

**Issue by tarnover** [jangaraj/Zabbix-Docker-Monitoring#14]
When importing either template on Ubuntu 14.04 with Zabbix 2.2.2 (MySQL) I get the following error when importing template.

    Created: Application "Docker" on "Template App Docker - active".
    mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
    Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:443]
    Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('Running containers','7','','','300','0','','','0','0','','0','','','','','0','','','','','',Array,'10','','docker.discovery','','10107','1','4','0',NULL,'23660')] [Unknown column 'Array' in 'field list']
    SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('Running containers','7','','','300','0','','','0','0','','0','','','','','0','','','','','',Array,'10','','docker.discovery','','10107','1','4','0',NULL,'23660')".

**Comment by jangaraj** [comment]
I will check it, when I have time. You have still option to create items, templates, triggers manually.

**Comment by jangaraj** [comment]
Zabbix 2.2 templates have been just added. Please test.
