### ISSUE TITLE
for debian

### ISSUE THREAD

**Issue by LichBanned** [jangaraj/Zabbix-Docker-Monitoring#8]
uname -a:
Linux 3.16.0-4-amd64 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux

// found line e.g. cgroup /cgroup/cpuacct cgroup rw,relatime,cpuacct 0 0
For debian line is:
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0

full list:

rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,relatime,size=10240k,nr_inodes=255186,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,relatime,size=411720k,mode=755 0 0
/dev/disk/by-uuid/9a7fd20b-faed-4c65-b8cb-f7efc38ce27a / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=21,pgrp=1,timeout=300,minproto=5,maxproto=5,direct 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
/dev/disk/by-uuid/9a7fd20b-faed-4c65-b8cb-f7efc38ce27a /var/lib/docker/aufs ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
none /var/lib/docker/aufs/mnt/127eab9c9f85d11f68aaaec76f536b3d04b4d6f7d4893111bd2a65218b7ef24a aufs rw,relatime,si=c0061a75a25ac11e 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
none /var/lib/docker/aufs/mnt/375d7627e9922a6a3a0bb31ca660381dadf84c02aade2ee0f3061daabf577a04 aufs rw,relatime,si=c0061a75a24e611e 0 0
none /var/lib/docker/aufs/mnt/a23110ea8ca5a42194968a7190ffb55afd6b92c1954262d7becb821a0148cc5e aufs rw,relatime,si=c0061a75dcd7e11e 0 0

**Comment by jangaraj** [comment]
Did you try latest version? Could you provide zabbix-agent.log (debug=4) please? I would like to see logs from start of zabbix agent, when module is initialized.

Thx

**Comment by jangaraj** [comment]
No detail provided. I'm closing this issue. Please feel free to reopen and provide more details.
Cgroup mount point is detected from /proc/mounts automatically and I didn't find any problem with this functionality on Debian 7.
Default cgroup memory accounting is not enabled in 3.16.0-0.bpo.4-amd64, but this problem will be fixed soon.
