### ISSUE TITLE
zbx_module_docker_up not working on debian

### ISSUE THREAD

**Issue by netflash** [jangaraj/Zabbix-Docker-Monitoring#9]
Hi, it looks like due to "memory accounting is not available by default on Debian 7" this function is not working. It always return 0.
I also suggest if it can't get a result it's better to return ZBX_NOTSUPPORTED.

Here is a part of log file related to this
```
21270:20150401:115000.489 In zbx_module_docker_up()
 21270:20150401:115000.489 Metric source file: /sys/fs/cgroup/memory/docker/879964bb231a85fb37517b46a5ab8938cec21fc76ab8d07076b92e7fee6339d8/memory.stat
 21270:20150401:115000.489 Can't open Docker container metric file: '/sys/fs/cgroup/memory/docker/879964bb231a85fb37517b46a5ab8938cec21fc76ab8d07076b92e7fee6339d8/memory.stat', cont
ainer doesn't run
 21270:20150401:115000.489 for key [docker.up[879964bb231a85fb37517b46a5ab8938cec21fc76ab8d07076b92e7fee6339d8]] received value [0.000000]
 21270:20150401:115000.489 In process_value() key:'hostname:docker.up[879964bb231a85fb37517b46a5ab8938cec21fc76ab8d07076b92e7fee6339d8]' value:'0.000000'
```

**Comment by jangaraj** [comment]
You are right. Fixed: pseudo file cpuacct.stat is used now. I can't return not supported, because that's the test. If file exists - container is up, if file doesn't exist - container is down.

**Comment by netflash** [comment]
Fix is working good. Thanks. But there's still issue with UNSUPPORTED - when container is already deleted (discover will delete it from items minimum in 24 hours), it show DOWN.
I'll sugest maybe first check "IF DIRECTORY EXIST" then check file, ELSE UNSUPPORTED.

**Comment by jangaraj** [comment]
Current behavior, when container is stopped or deleted:
docker.up -> 0 (IMHO not supported is the best return value, because then Zabbix is not able to create graph)
docker.cpu, docker.mem, docker.dev -> not supported

**Comment by jangaraj** [comment]
I'm closing this issue. I didn't find logical reason for UNSUPPORTED value, when container is not running. Also 0 value can be used in trigger condition, which won't be possible if function return UNSUPPORTED value , e.g. it's a problem only when container is UP (docker.up[fci]==1).
If someone can provide better arguments, then it can be modified.
Feel free to create feature request in the future.
